# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hand_pb2 as hand__pb2


class DealerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Deal = channel.unary_unary(
                '/deal_app.Dealer/Deal',
                request_serializer=hand__pb2.HandRequest.SerializeToString,
                response_deserializer=hand__pb2.HandResponse.FromString,
                )


class DealerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Deal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DealerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Deal': grpc.unary_unary_rpc_method_handler(
                    servicer.Deal,
                    request_deserializer=hand__pb2.HandRequest.FromString,
                    response_serializer=hand__pb2.HandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deal_app.Dealer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dealer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Deal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deal_app.Dealer/Deal',
            hand__pb2.HandRequest.SerializeToString,
            hand__pb2.HandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
