# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hand.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/hand.proto\x12\x08\x64\x65\x61l_app\"\"\n\x0bHandRequest\x12\x13\n\x0bplayerCount\x18\x01 \x01(\x05\"9\n\x04Hand\x12\r\n\x05\x63\x61rds\x18\x01 \x03(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"2\n\x05\x42oard\x12\x0c\n\x04\x66lop\x18\x01 \x03(\t\x12\x0c\n\x04turn\x18\x02 \x01(\t\x12\r\n\x05river\x18\x03 \x01(\t\"M\n\x0cHandResponse\x12\x1e\n\x05\x62oard\x18\x01 \x01(\x0b\x32\x0f.deal_app.Board\x12\x1d\n\x05hands\x18\x02 \x03(\x0b\x32\x0e.deal_app.Hand2A\n\x06\x44\x65\x61ler\x12\x37\n\x04\x44\x65\x61l\x12\x15.deal_app.HandRequest\x1a\x16.deal_app.HandResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.hand_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HANDREQUEST']._serialized_start=30
  _globals['_HANDREQUEST']._serialized_end=64
  _globals['_HAND']._serialized_start=66
  _globals['_HAND']._serialized_end=123
  _globals['_BOARD']._serialized_start=125
  _globals['_BOARD']._serialized_end=175
  _globals['_HANDRESPONSE']._serialized_start=177
  _globals['_HANDRESPONSE']._serialized_end=254
  _globals['_DEALER']._serialized_start=256
  _globals['_DEALER']._serialized_end=321
# @@protoc_insertion_point(module_scope)
