# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hand.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/hand.proto',
  package='deal_app',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10proto/hand.proto\x12\x08\x64\x65\x61l_app\"\"\n\x0bHandRequest\x12\x13\n\x0bplayerCount\x18\x01 \x01(\x05\"9\n\x04Hand\x12\r\n\x05\x63\x61rds\x18\x01 \x03(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"2\n\x05\x42oard\x12\x0c\n\x04\x66lop\x18\x01 \x03(\t\x12\x0c\n\x04turn\x18\x02 \x01(\t\x12\r\n\x05river\x18\x03 \x01(\t\"M\n\x0cHandResponse\x12\x1e\n\x05\x62oard\x18\x01 \x01(\x0b\x32\x0f.deal_app.Board\x12\x1d\n\x05hands\x18\x02 \x03(\x0b\x32\x0e.deal_app.Hand2A\n\x06\x44\x65\x61ler\x12\x37\n\x04\x44\x65\x61l\x12\x15.deal_app.HandRequest\x1a\x16.deal_app.HandResponse\"\x00\x62\x06proto3'
)




_HANDREQUEST = _descriptor.Descriptor(
  name='HandRequest',
  full_name='deal_app.HandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerCount', full_name='deal_app.HandRequest.playerCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=64,
)


_HAND = _descriptor.Descriptor(
  name='Hand',
  full_name='deal_app.Hand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cards', full_name='deal_app.Hand.cards', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='deal_app.Hand.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='deal_app.Hand.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=123,
)


_BOARD = _descriptor.Descriptor(
  name='Board',
  full_name='deal_app.Board',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flop', full_name='deal_app.Board.flop', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='turn', full_name='deal_app.Board.turn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='river', full_name='deal_app.Board.river', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=175,
)


_HANDRESPONSE = _descriptor.Descriptor(
  name='HandResponse',
  full_name='deal_app.HandResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='board', full_name='deal_app.HandResponse.board', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hands', full_name='deal_app.HandResponse.hands', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=254,
)

_HANDRESPONSE.fields_by_name['board'].message_type = _BOARD
_HANDRESPONSE.fields_by_name['hands'].message_type = _HAND
DESCRIPTOR.message_types_by_name['HandRequest'] = _HANDREQUEST
DESCRIPTOR.message_types_by_name['Hand'] = _HAND
DESCRIPTOR.message_types_by_name['Board'] = _BOARD
DESCRIPTOR.message_types_by_name['HandResponse'] = _HANDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HandRequest = _reflection.GeneratedProtocolMessageType('HandRequest', (_message.Message,), {
  'DESCRIPTOR' : _HANDREQUEST,
  '__module__' : 'proto.hand_pb2'
  # @@protoc_insertion_point(class_scope:deal_app.HandRequest)
  })
_sym_db.RegisterMessage(HandRequest)

Hand = _reflection.GeneratedProtocolMessageType('Hand', (_message.Message,), {
  'DESCRIPTOR' : _HAND,
  '__module__' : 'proto.hand_pb2'
  # @@protoc_insertion_point(class_scope:deal_app.Hand)
  })
_sym_db.RegisterMessage(Hand)

Board = _reflection.GeneratedProtocolMessageType('Board', (_message.Message,), {
  'DESCRIPTOR' : _BOARD,
  '__module__' : 'proto.hand_pb2'
  # @@protoc_insertion_point(class_scope:deal_app.Board)
  })
_sym_db.RegisterMessage(Board)

HandResponse = _reflection.GeneratedProtocolMessageType('HandResponse', (_message.Message,), {
  'DESCRIPTOR' : _HANDRESPONSE,
  '__module__' : 'proto.hand_pb2'
  # @@protoc_insertion_point(class_scope:deal_app.HandResponse)
  })
_sym_db.RegisterMessage(HandResponse)



_DEALER = _descriptor.ServiceDescriptor(
  name='Dealer',
  full_name='deal_app.Dealer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=256,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='Deal',
    full_name='deal_app.Dealer.Deal',
    index=0,
    containing_service=None,
    input_type=_HANDREQUEST,
    output_type=_HANDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEALER)

DESCRIPTOR.services_by_name['Dealer'] = _DEALER

# @@protoc_insertion_point(module_scope)
